# Generated by Django 6.0 on 2026-01-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(default='000000', max_length=128),
        ),
    ]
